import Head from 'next/head'
import Hero from '../components/Hero'
import Gallery from '../components/Gallery'
import Locations from '../components/Locations'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Nature</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero   
        heading="Nature's Beauty" 
        message="The beauty of nature captured in a selection of photographs."
      />
      <Gallery />
      <Locations />
    </div>
  )
}
